# Generated by Django 5.2.1 on 2025-06-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_record_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='zip_code',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='perchase_price',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='first_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='city',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='phone',
            new_name='selling_price',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='created_at',
            new_name='sold_At',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='state',
            new_name='warranty_period',
        ),
        migrations.RemoveField(
            model_name='record',
            name='email',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
        migrations.AddField(
            model_name='record',
            name='product_Price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
